### PR TITLE
Helm chart: SecurityContext configurable

### PR DESCRIPTION
**Pull request by Gianluca755**
- [ ] Tests written and linted [ℹ︎](https://github.com/snyk/general/wiki/Tests)
- [ ] Documentation written [ℹ︎](https://github.com/snyk/general/wiki/Documentation)
- [ ] Commit history is tidy [ℹ︎](https://github.com/snyk/general/wiki/Git)

The above links are broken!

### What this does

Resolve https://github.com/snyk/kubernetes-monitor/issues/1518.

### CODE REVIEW

**Review by jonnyowenpowell — COMMENTED** [review]
Thanks for the contribution!

We would like to retain compatibility with the current `securityContext.fsGroup` value. As such, could I ask that the PR be updated to use and give precedence to that value, when it is set, as follows:
```
{{- with .Values.podSecurityContext }}
securityContext:
{{- $fsGroupOverride := dict }}
{{- if hasKey $.Values.securityContext "fsGroup" }}
{{- $fsGroupOverride = dict "fsGroup" (int $.Values.securityContext.fsGroup) }}
{{- end }}
{{- merge $fsGroupOverride . | toYaml | nindent 8 }}
{{- else }}
{{- if .Values.securityContext.fsGroup }}
securityContext:
  fsGroup: {{ int .Values.securityContext.fsGroup }}
{{- end }}
{{- end }}
```

**Comment by Gianluca755** [comment]
@jonnyowenpowell like this?

**Review by jonnyowenpowell — APPROVED** [review]
LGTM 👍

**Comment by jonnyowenpowell** [comment]
I've cherry-picked and raised this separately in the PR linked above to avoid back-and-forth on non-functional issues like targeting the `staging` branch and having commit messages pass linting.

Thanks very much for the contribution 🙏
 
I'll update here when it's deployed.

**Comment by jonnyowenpowell** [comment]
This has been deployed with this release: #1525.

**Pull request closed without merging**
